server:
  port: 8080

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none

spring:
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: golepel@$amp
  thymeleaf:
    mode: HTML
debug: true



  sms.serviceid = /sms/v2/services/ncp:sms:kr:255444522560:bankbit/messages
  sms.accesskey = wTottmhcykh5RKYvc2z6
  sms.secretkey = dDIu2LK1JOhBp9Kv4YNWRYsNNPmWLAPalvXZWKbD