server:
  port: 8080

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none

spring:
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: golepel@$amp
  thymeleaf:
    mode: HTML
  datasource:
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
  jpa:
    hibernate:
      ddl-auto: update
debug: true

