--
-- INSERT INTO Post VALUES (1, '테스트 제목 1', '테스트 내용 1');
-- INSERT INTO Post VALUES (2, '테스트 제목 2', '테스트 내용 2');
-- INSERT INTO Post VALUES (3, '테스트 제목 3', '테스트 내용 3');
-- INSERT INTO Post VALUES (4, '테스트 제목 4', '테스트 내용 4');
-- INSERT INTO Post VALUES (5, '테스트 제목 5', '테스트 내용 5');
-- INSERT INTO Post VALUES (6, '테스트 제목 6', '테스트 내용 6');
-- INSERT INTO Post VALUES (7, '테스트 제목 7', '테스트 내용 7');
--
-- INSERT INTO Comment VALUES (1, 1, '테스트 댓글 1');
-- INSERT INTO Comment VALUES (2, 1, '테스트 댓글 2');
-- INSERT INTO Comment VALUES (3, 1, '테스트 댓글 3');
-- INSERT INTO Comment VALUES (4, 1, '테스트 댓글 4');
-- INSERT INTO Comment VALUES (5, 1, '테스트 댓글 5');
-- INSERT INTO Comment VALUES (6, 1, '테스트 댓글 6');
--
--
